# Connect to web page

In [67]:
import requests
from bs4 import BeautifulSoup

url = "https://www.redfin.com/state/California/apartments-for-rent/filter/viewport=38.13751:37.17207:-121.37222:-123.06412"

headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"}

# Make a request to the website
response = requests.get(url, headers=headers)



# Parse the HTML content of the webpage
soup = BeautifulSoup(response.content, 'html.parser')

soup1 = BeautifulSoup(soup.prettify(),'html.parser')

# Extract the price, address and home stats
price = soup1.find(class_='homecardV2Price').get_text()
address = soup1.find(class_='homeAddressV2').get_text()
homestats = soup1.find(class_='HomeStatsV2 font-size-small').get_text()

stats = soup1.find(class_='stats').get_text()

print(stats)

                1-2 Bed

# Scrape rental data

In [2]:
#Scrape rental data from all 9 pages

In [ ]:
for i in range(1,10):
    urll = f"https://www.redfin.com/state/California/apartments-for-rent/filter/viewport=38.13751:37.17207:-121.37222:-123.06412/page-{i}"
    responses = requests.get(urll, headers=headers)
    soup = BeautifulSoup(responses.content, 'html.parser')

    prices = [item.get_text() for item in soup.find_all(class_='homecardV2Price')]
    addresses = [item.get_text() for item in soup.find_all(class_='homeAddressV2')]
    homestats = [item.get_text() for item in soup.find_all(class_='HomeStatsV2 font-size-small')]

    for j in range(len(prices)):
        if j == 10:
            break
        print("Price:", prices[j])
        print("Address:", addresses[j])
        print("Home Stats:", homestats[j])

Price: $3,065-$5,890/mo
Address: Redwood Place | 1030 Indian Wells Ave, Sunnyvale, CA 94085
Home Stats: 1-2 Bed1-2 Bath563-1,276 Sq. Ft.
Price: $3,235-$5,965/mo
Address: Santa Clara Square | 3320 Montgomery Dr, Santa Clara, CA 95054
Home Stats: 0-2 Beds1-2 Bath608-1,816 Sq. Ft.
Price: $3,270-$4,555/mo
Address: The Triton | 55 Triton Park Ln, Foster City, CA 94404
Home Stats: 1-2 Bed1-2.5 Bath760-1,147 Sq. Ft.
Price: $2,611-$3,362/mo
Address: Woodland Meadow | 1600 Whitewood Dr, San Jose, CA 95131
Home Stats: 1-2 Bed1-2 Bath836-1,119 Sq. Ft.
Price: $3,060-$4,695/mo
Address: Monticello | 3515-3585 Monroe St, Santa Clara, CA 95051
Home Stats: 1-2 Bed1-2 Bath795-1,408 Sq. Ft.
Price: $3,877-$6,614/mo
Address: The Hadley | 555 E Evelyn Ave, Mountain View, CA 94041
Home Stats: 0-3 Beds1-2 Bath644-1,355 Sq. Ft.
Price: $3,340-$3,650/mo
Address: The Blossoms at Brentwood | 2255 Amber Ln, Brentwood, CA 94513
Home Stats: 2-3 Beds2 Baths922-1,251 Sq. Ft.
Price: $3,157-$4,809/mo
Address: Edgewater | 355 Berry St, San Francisco, CA 94158
Home Stats: 1-2 Bed1-2 Bath535-1,330 Sq. Ft.
Price: $3,145-$4,420/mo
Address: Cherry Orchard | 250 W El Camino Real, Sunnyvale, CA 94087
Home Stats: 1-2 Bed1-2 Bath761-1,104 Sq. Ft.
Price: $4,874-$7,857/mo
Address: Sharon Green | 350 Sharon Park Dr, Menlo Park, CA 94025
Home Stats: 1-3 Bed1-2 Bath810-1,466 Sq. Ft.
Price: $2,791-$4,986/mo
Address: The Madelon | 2000 Bryant St, San Francisco, CA 94110
Home Stats: 0-2 Beds1-2 Bath435-963 Sq. Ft.
Price: $2,549-$5,668/mo
Address: Parkmerced Apartments | 3711 19th Ave, San Francisco, CA 94132
Home Stats: 1-3 Bed1-3 Bath691-1,411 Sq. Ft.
Price: $2,955-$4,645/mo
Address: Renaissance | 718 Old San Francisco Rd, Sunnyvale, CA 94086
Home Stats: 1-3 Bed1-3 Bath808-1,387 Sq. Ft.
Price: $2,295/mo
Address: Westmont of Milpitas | 80 Cedar Way, Milpitas, CA 95035
Home Stats: 0-2 Beds0-2 Baths—Sq. Ft.
Price: $4,449-$6,229/mo
Address: Preserve at Marin Apartment Homes | 300 Robin Dr, Corte Madera, CA 94925
Home Stats: 2-3 Beds2 Baths1,367-1,549 Sq. Ft.
Price: $3,413-$3,962/mo
Address: 707 Leahy Apartments | 707 Leahy St, Redwood City, CA 94061
Home Stats: 1-2 Bed1 Bath638-840 Sq. Ft.
Price: $3,445/mo
Address: Anton 1101 | 1101 N Fair Oaks Ave, Sunnyvale, CA 94089
Home Stats: 1 Bed1 Bath738 Sq. Ft.
Price: $2,361-$3,343/mo
Address: Laguna Clara | 3131 Homestead Rd, Santa Clara, CA 95051
Home Stats: 1-2 Bed1-2 Bath712-1,158 Sq. Ft.
Price: $2,835-$6,150/mo
Address: 399 Fremont St, San Francisco, CA 94105
Home Stats: 0-2 Beds1-2.5 Bath450-1,540 Sq. Ft.
Price: $3,028-$3,985/mo
Address: The Mason Flats | 1605 Lexington Ln, Pleasanton, CA 94588
Home Stats: 1-2 Bed1-2 Bath729-1,135 Sq. Ft.
Price: $2,749/mo
Address: Furnished Studio - San Francisco - San Mateo - SFO | 1830 Gateway Dr, San Mateo, CA 94404
Home Stats: 0 Beds1 Bath270 Sq. Ft.
Price: $2,436-$3,009/mo
Address: Mill Springs Park | 1809 Railroad Ave, Livermore, CA 94550
Home Stats: 1-2 Bed1-2 Bath665-953 Sq. Ft.
Price: $3,000/mo
Address: Furnished Studio - San Ramon - Bishop Ranch - East | 2100 Camino Ramon, San Ramon, CA 94583
Home Stats: 0 Beds1 Bath300 Sq. Ft.
Price: $3,150/mo
Address: 8 Admiral Dr Unit 327, Emeryville, CA 94608
Home Stats: 2 Beds1.5 Baths877 Sq. Ft.
Price: $3,100-$3,548/mo
Address: Southwood | 2850 Middlefield Rd, Palo Alto, CA 94306
Home Stats: 1-2 Bed1-2 Bath750-980 Sq. Ft.
Price: $3,089-$6,309/mo
Address: 388 Beale St, San Francisco, CA 94105
Home Stats: 0-2 Beds1-2.5 Bath400-1,673 Sq. Ft.
Price: $3,165-$7,474/mo
Address: 950 Tennessee St, San Francisco, CA 94107
Home Stats: 0-3 Beds1-2.5 Bath432-1,440 Sq. Ft.
Price: $2,295/mo
Address: 537 A St, Hayward, CA 94541
Home Stats: 2 Beds1 Bath800 Sq. Ft.
Price: $2,795-$2,895/mo
Address: Los Gatos Gardens | 14850 Oka Rd, Los Gatos, CA 95032
Home Stats: 2 Beds1 Bath815 Sq. Ft.
Price: $2,310/mo
Address: Furnished Studio - San Ramon - Bishop Ranch - West | 18000 San Ramon Valley Blvd, San Ramon, CA 94583
Home Stats: 0 Beds1 Bath270 Sq. Ft.
Price: $3,295/mo
Address: Village Square Townhouses | 1674 Hollenbeck Ave, Sunnyvale, CA 94087
Home Stats: 2 Beds1 Bath1,000 Sq. Ft.
Price: $2,735-$4,710/mo
Address: Avalon Silicon Valley | 1257 Lakeside Dr, Sunnyvale, CA 94085
Home Stats: 1-3 Bed1-3 Bath700-1,335 Sq. Ft.
Price: $2,395-$5,395/mo
Address: The Highlander | 620 Iris Ave, Sunnyvale, CA 94086
Home Stats: 1-3 Bed1-2 Bath677-1,159 Sq. Ft.
Price: $2,695/mo
Address: 2925 Van Ness Ave, San Francisco, CA 94109
Home Stats: 1 Bed1 Bath—Sq. Ft.
Price: $2,760-$4,243/mo
Address: Vista 99 | 99 Vista Montana, San Jose, CA 95134
Home Stats: 1-3 Bed1-3 Bath740-1,430 Sq. Ft.
Price: $2,538-$2,879/mo
Address: Ballena Village | 335 Tideway Dr, Alameda, CA 94501
Home Stats: 1-2 Bed1 Bath615-773 Sq. Ft.
Price: $2,400-$3,000/mo
Address: Macara Gardens | 955 Escalon Ave, Sunnyvale, CA 94085
Home Stats: 1-2 Bed1-2 Bath658-903 Sq. Ft.
Price: $1,195/mo
Address: 1335 Filbert St #106, San Francisco, CA 94109
Home Stats: 2 Beds2 Baths1,961 Sq. Ft.
Price: $2,729-$4,249/mo
Address: River Terrace | 730 Agnew Rd, Santa Clara, CA 95054
Home Stats: 1-3 Bed1-2 Bath719-1,496 Sq. Ft.
Price: $2,580/mo
Address: Furnished Studio - Union City - Dyer St. | 31950 Dyer St, Union City, CA 94587
Home Stats: 0 Beds1 Bath300 Sq. Ft.
Price: $2,039-$2,501/mo
Address: Heritage Park Livermore for Seniors | 1089 Bluebell Dr, Livermore, CA 94551
Home Stats: 1-2 Bed1 Bath460-699 Sq. Ft.
Price: $2,235-$2,860/mo
Address: 1490 Bel Air Dr, Concord, CA 94521
Home Stats: 1-2 Bed1-2 Bath693-848 Sq. Ft.
Price: $2,863-$3,934/mo
Address: One Pearl Place | 5230 Terner Way, San Jose, CA 95136
Home Stats: 1-2 Bed1-2 Bath778-1,200 Sq. Ft.
Price: $3,195/mo
Address: 555 Fulton St #406, San Francisco, CA 94102
Home Stats: 1 Bed1 Bath500 Sq. Ft.
Price: $2,392-$3,123/mo
Address: Colonial Garden | 460 N Humboldt St, San Mateo, CA 94401
Home Stats: 1-3 Bed1-1.5 Bath535-917 Sq. Ft.
Price: $2,085-$3,155/mo
Address: Lakeshore | 600 Wilbur Ave, Antioch, CA 94509
Home Stats: 1-3 Bed1-2 Bath700-1,178 Sq. Ft.
Price: $2,165-$3,935/mo
Address: eaves Mountain View at Middlefield | 555 W Middlefield Rd, Mountain View, CA 94043
Home Stats: 0-2 Beds1-2 Bath405-1,048 Sq. Ft.
Price: $1,700/mo
Address: 626 Pine St Unit 203, San Francisco, CA 94108
Home Stats: 0 Beds1 Bath—Sq. Ft.
Price: $2,950/mo
Address: Station 101 | 3700 Lillick Dr, Santa Clara, CA 95051
Home Stats: 2 Beds2 Baths1,120 Sq. Ft.
Price: $2,197-$5,894/mo
Address: Tower 737 | 737 Post St, San Francisco, CA 94109
Home Stats: 0-2 Beds1-2 Bath326-710 Sq. Ft.

# Structure data and export into CSV file

In [6]:
import requests
from bs4 import BeautifulSoup
import csv

headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"}

data = []

for i in range(1, 10):
    url = f"https://www.redfin.com/state/California/apartments-for-rent/filter/viewport=38.13751:37.17207:-121.37222:-123.06412/page-{i}"
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    prices = [item.get_text() for item in soup.find_all(class_='homecardV2Price')]
    addresses = [item.get_text() for item in soup.find_all(class_='homeAddressV2')]
    homestats = [item.get_text() for item in soup.find_all(class_='HomeStatsV2 font-size-small')]

    for j in range(len(prices)):
        data.append([prices[j], addresses[j], homestats[j]])

with open("apartment_data.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Price", "Address", "Home Stats"])
    writer.writerows(data)



print("created")

created

# Import excel file

In [69]:
import pandas as pd
#converted the csv file to an excel file instead because pandas was having trouble reading it
dff = pd.read_excel('redfinbayrentals.xlsx', sheet_name='redfin')

print(dff.head(10))

              Price                                            Address  \
0  $4,472-$8,057/mo  Sharon Green | 350 Sharon Park Dr, Menlo Park,...
1  $3,305-$5,380/mo  The Triton | 55 Triton Park Ln, Foster City, C...
2  $3,085-$6,080/mo  Redwood Place | 1030 Indian Wells Ave, Sunnyva...
3         $7,300/mo           570 La Mesa Dr, Portola Valley, CA 94028
4  $3,877-$6,563/mo  The Hadley | 555 E Evelyn Ave, Mountain View, ...
5  $3,340-$3,650/mo  The Blossoms at Brentwood | 2255 Amber Ln, Bre...
6  $2,850-$7,375/mo    The Brady | 1 Brady St, San Francisco, CA 94103
7         $3,900/mo            2616 Royal Ann Dr, Union City, CA 94587
8  $3,355-$5,760/mo  Santa Clara Square | 3320 Montgomery Dr, Santa...
9  $3,055-$4,725/mo  Monticello | 3515-3585 Monroe St, Santa Clara,...

                           Home Stats
0    1-3 Bed1-2 Bath810-1,466 Sq. Ft.
1  1-3 Bed1-2.5 Bath760-1,392 Sq. Ft.
2    1-2 Bed1-2 Bath563-1,276 Sq. Ft.
3          3 Beds2 Baths1,740 Sq. Ft.
4   0-3 Beds1-2 Bath644-1,355 Sq. Ft.
5    2-3 Beds2 Baths922-1,251 Sq. Ft.
6   0-2 Beds1-2 Bath447-1,575 Sq. Ft.
7          4 Beds2 Baths2,169 Sq. Ft.
8   0-2 Beds1-2 Bath608-1,537 Sq. Ft.
9    1-2 Bed1-2 Bath798-1,408 Sq. Ft.

# Data cleaning and restructuring

In [70]:
# remove the '|'' and every string before it from values in the "Address" column
dff['Address'] = dff['Address'].str.split('|').str[-1]


dff

,Price,Address,Home Stats
0,"$4,472-$8,057/mo","350 Sharon Park Dr, Menlo Park, CA 94025","1-3 Bed1-2 Bath810-1,466 Sq. Ft."
1,"$3,305-$5,380/mo","55 Triton Park Ln, Foster City, CA 94404","1-3 Bed1-2.5 Bath760-1,392 Sq. Ft."
2,"$3,085-$6,080/mo","1030 Indian Wells Ave, Sunnyvale, CA 94085","1-2 Bed1-2 Bath563-1,276 Sq. Ft."
3,"$7,300/mo","570 La Mesa Dr, Portola Valley, CA 94028","3 Beds2 Baths1,740 Sq. Ft."
4,"$3,877-$6,563/mo","555 E Evelyn Ave, Mountain View, CA 94041","0-3 Beds1-2 Bath644-1,355 Sq. Ft."
...,...,...,...
315,"$3,000/mo","425 2nd Ave, San Francisco, CA 94118",1 Bed1 Bath851 Sq. Ft.
316,"$2,900/mo","280 Easy St #501, Mountain View, CA 94043",2 Beds1 Bath894 Sq. Ft.
317,"$6,850/mo","6840 Charing Cross Rd, Berkeley, CA 94705","5 Beds3.5 Baths3,908 Sq. Ft."
318,"$12,000/mo","111 30th Ave, San Francisco, CA 94121","4 Beds3 Baths3,100 Sq. Ft."
319,"$3,450/mo","1320 Windswept Cmn, Livermore, CA 94550","3 Beds3.5 Baths1,757 Sq. Ft."

In [71]:
# split the values in the "Address" column of the DataFrame dff into separate columns for "Address", "City", and "State".
dff['Address'].str.rsplit(',', 2).apply(lambda x: x[0] if len(x) == 3 else x[0] + ',' + x[1])
dff = dff.assign(
    Address=dff['Address'].str.rsplit(',', 2).apply(lambda x: x[0] if len(x) == 3 else x[0] + ',' + x[1]),
    City=dff['Address'].str.rsplit(',', 2).apply(lambda x: x[1] if len(x) == 3 else None),
    State=dff['Address'].str.rsplit(',', 2).apply(lambda x: x[2] if len(x) == 3 else None)
)
dff

C:\Users\yaboy\AppData\Local\Temp\ipykernel_9628\627500783.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.rsplit except for the argument 'pat' will be keyword-only.
  dff['Address'].str.rsplit(',', 2).apply(lambda x: x[0] if len(x) == 3 else x[0] + ',' + x[1])
C:\Users\yaboy\AppData\Local\Temp\ipykernel_9628\627500783.py:4: FutureWarning: In a future version of pandas all arguments of StringMethods.rsplit except for the argument 'pat' will be keyword-only.
  Address=dff['Address'].str.rsplit(',', 2).apply(lambda x: x[0] if len(x) == 3 else x[0] + ',' + x[1]),
C:\Users\yaboy\AppData\Local\Temp\ipykernel_9628\627500783.py:5: FutureWarning: In a future version of pandas all arguments of StringMethods.rsplit except for the argument 'pat' will be keyword-only.
  City=dff['Address'].str.rsplit(',', 2).apply(lambda x: x[1] if len(x) == 3 else None),
C:\Users\yaboy\AppData\Local\Temp\ipykernel_9628\627500783.py:6: FutureWarning: In a future version of pandas all arguments of StringMethods.rsplit except for the argument 'pat' will be keyword-only.
  State=dff['Address'].str.rsplit(',', 2).apply(lambda x: x[2] if len(x) == 3 else None)

,Price,Address,Home Stats,City,State
0,"$4,472-$8,057/mo",350 Sharon Park Dr,"1-3 Bed1-2 Bath810-1,466 Sq. Ft.",Menlo Park,CA 94025
1,"$3,305-$5,380/mo",55 Triton Park Ln,"1-3 Bed1-2.5 Bath760-1,392 Sq. Ft.",Foster City,CA 94404
2,"$3,085-$6,080/mo",1030 Indian Wells Ave,"1-2 Bed1-2 Bath563-1,276 Sq. Ft.",Sunnyvale,CA 94085
3,"$7,300/mo",570 La Mesa Dr,"3 Beds2 Baths1,740 Sq. Ft.",Portola Valley,CA 94028
4,"$3,877-$6,563/mo",555 E Evelyn Ave,"0-3 Beds1-2 Bath644-1,355 Sq. Ft.",Mountain View,CA 94041
...,...,...,...,...,...
315,"$3,000/mo",425 2nd Ave,1 Bed1 Bath851 Sq. Ft.,San Francisco,CA 94118
316,"$2,900/mo",280 Easy St #501,2 Beds1 Bath894 Sq. Ft.,Mountain View,CA 94043
317,"$6,850/mo",6840 Charing Cross Rd,"5 Beds3.5 Baths3,908 Sq. Ft.",Berkeley,CA 94705
318,"$12,000/mo",111 30th Ave,"4 Beds3 Baths3,100 Sq. Ft.",San Francisco,CA 94121
319,"$3,450/mo",1320 Windswept Cmn,"3 Beds3.5 Baths1,757 Sq. Ft.",Livermore,CA 94550

In [72]:
# extract the ZipCode from the "State" column of the DataFrame dff and then remove it from the "State" column, creates a new column for the zip code
dff['ZipCode'] = dff['State'].str.extract(r'(\d{5})')
dff['State'] = dff['State'].str.replace(r' \d{5}', '')

dff

C:\Users\yaboy\AppData\Local\Temp\ipykernel_9628\1065006877.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  dff['State'] = dff['State'].str.replace(r' \d{5}', '')

,Price,Address,Home Stats,City,State,ZipCode
0,"$4,472-$8,057/mo",350 Sharon Park Dr,"1-3 Bed1-2 Bath810-1,466 Sq. Ft.",Menlo Park,CA,94025
1,"$3,305-$5,380/mo",55 Triton Park Ln,"1-3 Bed1-2.5 Bath760-1,392 Sq. Ft.",Foster City,CA,94404
2,"$3,085-$6,080/mo",1030 Indian Wells Ave,"1-2 Bed1-2 Bath563-1,276 Sq. Ft.",Sunnyvale,CA,94085
3,"$7,300/mo",570 La Mesa Dr,"3 Beds2 Baths1,740 Sq. Ft.",Portola Valley,CA,94028
4,"$3,877-$6,563/mo",555 E Evelyn Ave,"0-3 Beds1-2 Bath644-1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,"$3,000/mo",425 2nd Ave,1 Bed1 Bath851 Sq. Ft.,San Francisco,CA,94118
316,"$2,900/mo",280 Easy St #501,2 Beds1 Bath894 Sq. Ft.,Mountain View,CA,94043
317,"$6,850/mo",6840 Charing Cross Rd,"5 Beds3.5 Baths3,908 Sq. Ft.",Berkeley,CA,94705
318,"$12,000/mo",111 30th Ave,"4 Beds3 Baths3,100 Sq. Ft.",San Francisco,CA,94121
319,"$3,450/mo",1320 Windswept Cmn,"3 Beds3.5 Baths1,757 Sq. Ft.",Livermore,CA,94550

In [73]:
# replace values in the 'Home Stats' column of a Pandas DataFrame dff. The argument r'\d+-' is a regular expression pattern that matches one or more consecutive digits (\d+) followed by a hyphen (-).

dff['Home Stats'] = dff['Home Stats'].str.replace(r'\d+-', '')

dff

C:\Users\yaboy\AppData\Local\Temp\ipykernel_9628\78441521.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  dff['Home Stats'] = dff['Home Stats'].str.replace(r'\d+-', '')

,Price,Address,Home Stats,City,State,ZipCode
0,"$4,472-$8,057/mo",350 Sharon Park Dr,"3 Bed2 Bath1,466 Sq. Ft.",Menlo Park,CA,94025
1,"$3,305-$5,380/mo",55 Triton Park Ln,"3 Bed2.5 Bath1,392 Sq. Ft.",Foster City,CA,94404
2,"$3,085-$6,080/mo",1030 Indian Wells Ave,"2 Bed2 Bath1,276 Sq. Ft.",Sunnyvale,CA,94085
3,"$7,300/mo",570 La Mesa Dr,"3 Beds2 Baths1,740 Sq. Ft.",Portola Valley,CA,94028
4,"$3,877-$6,563/mo",555 E Evelyn Ave,"3 Beds2 Bath1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,"$3,000/mo",425 2nd Ave,1 Bed1 Bath851 Sq. Ft.,San Francisco,CA,94118
316,"$2,900/mo",280 Easy St #501,2 Beds1 Bath894 Sq. Ft.,Mountain View,CA,94043
317,"$6,850/mo",6840 Charing Cross Rd,"5 Beds3.5 Baths3,908 Sq. Ft.",Berkeley,CA,94705
318,"$12,000/mo",111 30th Ave,"4 Beds3 Baths3,100 Sq. Ft.",San Francisco,CA,94121
319,"$3,450/mo",1320 Windswept Cmn,"3 Beds3.5 Baths1,757 Sq. Ft.",Livermore,CA,94550

In [74]:
# change the name of a column in the dff DataFrame.
dff.rename(columns={"Home Stats": "Size"}, inplace=True)
dff

,Price,Address,Size,City,State,ZipCode
0,"$4,472-$8,057/mo",350 Sharon Park Dr,"3 Bed2 Bath1,466 Sq. Ft.",Menlo Park,CA,94025
1,"$3,305-$5,380/mo",55 Triton Park Ln,"3 Bed2.5 Bath1,392 Sq. Ft.",Foster City,CA,94404
2,"$3,085-$6,080/mo",1030 Indian Wells Ave,"2 Bed2 Bath1,276 Sq. Ft.",Sunnyvale,CA,94085
3,"$7,300/mo",570 La Mesa Dr,"3 Beds2 Baths1,740 Sq. Ft.",Portola Valley,CA,94028
4,"$3,877-$6,563/mo",555 E Evelyn Ave,"3 Beds2 Bath1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,"$3,000/mo",425 2nd Ave,1 Bed1 Bath851 Sq. Ft.,San Francisco,CA,94118
316,"$2,900/mo",280 Easy St #501,2 Beds1 Bath894 Sq. Ft.,Mountain View,CA,94043
317,"$6,850/mo",6840 Charing Cross Rd,"5 Beds3.5 Baths3,908 Sq. Ft.",Berkeley,CA,94705
318,"$12,000/mo",111 30th Ave,"4 Beds3 Baths3,100 Sq. Ft.",San Francisco,CA,94121
319,"$3,450/mo",1320 Windswept Cmn,"3 Beds3.5 Baths1,757 Sq. Ft.",Livermore,CA,94550

In [75]:
# re format returns a formatted string based on the contents of s

import re 
def format_size(s):
    parts = re.findall(r'(\d+)\s*[Bb]ed.*?(\d+)\s*[Bb]ath.*?(\d+,\d+)\s*[Ss]q\s*[.]\s*[Ff]t\.', s)
    if parts:
        beds, baths, sqft = parts[0]
        return f"{beds} Beds, {baths} Baths, {sqft} Sq. Ft."
    return s

dff["Size"] = dff["Size"].apply(format_size)


dff

,Price,Address,Size,City,State,ZipCode
0,"$4,472-$8,057/mo",350 Sharon Park Dr,"3 Beds, 2 Baths, 1,466 Sq. Ft.",Menlo Park,CA,94025
1,"$3,305-$5,380/mo",55 Triton Park Ln,"3 Beds, 5 Baths, 1,392 Sq. Ft.",Foster City,CA,94404
2,"$3,085-$6,080/mo",1030 Indian Wells Ave,"2 Beds, 2 Baths, 1,276 Sq. Ft.",Sunnyvale,CA,94085
3,"$7,300/mo",570 La Mesa Dr,"3 Beds, 2 Baths, 1,740 Sq. Ft.",Portola Valley,CA,94028
4,"$3,877-$6,563/mo",555 E Evelyn Ave,"3 Beds, 2 Baths, 1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,"$3,000/mo",425 2nd Ave,1 Bed1 Bath851 Sq. Ft.,San Francisco,CA,94118
316,"$2,900/mo",280 Easy St #501,2 Beds1 Bath894 Sq. Ft.,Mountain View,CA,94043
317,"$6,850/mo",6840 Charing Cross Rd,"5 Beds, 5 Baths, 3,908 Sq. Ft.",Berkeley,CA,94705
318,"$12,000/mo",111 30th Ave,"4 Beds, 3 Baths, 3,100 Sq. Ft.",San Francisco,CA,94121
319,"$3,450/mo",1320 Windswept Cmn,"3 Beds, 5 Baths, 1,757 Sq. Ft.",Livermore,CA,94550

,Price,Address,Size,City,State,ZipCode
0,"$4,472-$8,057/mo",350 Sharon Park Dr,"3 Beds, 2 Baths, 1,466 Sq. Ft.",Menlo Park,CA,94025
1,"$3,305-$5,380/mo",55 Triton Park Ln,"3 Beds, 5 Baths, 1,392 Sq. Ft.",Foster City,CA,94404
2,"$3,085-$6,080/mo",1030 Indian Wells Ave,"2 Beds, 2 Baths, 1,276 Sq. Ft.",Sunnyvale,CA,94085
3,"$7,300/mo",570 La Mesa Dr,"3 Beds, 2 Baths, 1,740 Sq. Ft.",Portola Valley,CA,94028
4,"$3,877-$6,563/mo",555 E Evelyn Ave,"3 Beds, 2 Baths, 1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,"$3,000/mo",425 2nd Ave,1 Bed1 Bath851 Sq. Ft.,San Francisco,CA,94118
316,"$2,900/mo",280 Easy St #501,2 Beds1 Bath894 Sq. Ft.,Mountain View,CA,94043
317,"$6,850/mo",6840 Charing Cross Rd,"5 Beds, 5 Baths, 3,908 Sq. Ft.",Berkeley,CA,94705
318,"$12,000/mo",111 30th Ave,"4 Beds, 3 Baths, 3,100 Sq. Ft.",San Francisco,CA,94121
319,"$3,450/mo",1320 Windswept Cmn,"3 Beds, 5 Baths, 1,757 Sq. Ft.",Livermore,CA,94550

,Price,Address,Size,City,State,ZipCode
0,"$4,472-$8,057/mo",350 Sharon Park Dr,"3 Beds, 2 Baths, 1,466 Sq. Ft.",Menlo Park,CA,94025
1,"$3,305-$5,380/mo",55 Triton Park Ln,"3 Beds, 5 Baths, 1,392 Sq. Ft.",Foster City,CA,94404
2,"$3,085-$6,080/mo",1030 Indian Wells Ave,"2 Beds, 2 Baths, 1,276 Sq. Ft.",Sunnyvale,CA,94085
3,"$7,300/mo",570 La Mesa Dr,"3 Beds, 2 Baths, 1,740 Sq. Ft.",Portola Valley,CA,94028
4,"$3,877-$6,563/mo",555 E Evelyn Ave,"3 Beds, 2 Baths, 1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,"$3,000/mo",425 2nd Ave,"1 Beds, 1 Baths, 851 Sq. Ft.",San Francisco,CA,94118
316,"$2,900/mo",280 Easy St #501,"2 Beds, 1 Baths, 894 Sq. Ft.",Mountain View,CA,94043
317,"$6,850/mo",6840 Charing Cross Rd,"5 Beds, 5 Baths, 3,908 Sq. Ft.",Berkeley,CA,94705
318,"$12,000/mo",111 30th Ave,"4 Beds, 3 Baths, 3,100 Sq. Ft.",San Francisco,CA,94121
319,"$3,450/mo",1320 Windswept Cmn,"3 Beds, 5 Baths, 1,757 Sq. Ft.",Livermore,CA,94550

In [76]:
# reformat the values in the "Size" column by using string operations and regular expressions.

import re

def format_size(s):
    parts = re.findall(r'(\d+)\s*[Bb]ed.*?(\d+)\s*[Bb]ath.*?(\d+,\d+)\s*[Ss]q\s*[.]\s*[Ff]t\.', s)
    if parts:
        beds, baths, sqft = parts[0]
        if beds == '1':
            beds = '1 Bed'
        else:
            beds = f"{beds} Beds"
        if baths == '1':
            baths = '1 Bath'
        else:
            baths = f"{baths} Baths"
        return f"{beds}, {baths}, {int(sqft.replace(',', '')):,} Sq. Ft."
    parts = re.findall(r'(\d+)\s*[Bb]ed.*?(\d+)\s*[Bb]ath.*?(\d+)\s*[Ss]q\s*[.]\s*[Ff]t\.', s)
    if parts:
        beds, baths, sqft = parts[0]
        if beds == '1':
            beds = '1 Bed'
        else:
            beds = f"{beds} Beds"
        if baths == '1':
            baths = '1 Bath'
        else:
            baths = f"{baths} Baths"
        return f"{beds}, {baths}, {int(sqft):,} Sq. Ft."
    return s

dff["Size"] = dff["Size"].apply(format_size)

dff

,Price,Address,Size,City,State,ZipCode
0,"$4,472-$8,057/mo",350 Sharon Park Dr,"3 Beds, 2 Baths, 1,466 Sq. Ft.",Menlo Park,CA,94025
1,"$3,305-$5,380/mo",55 Triton Park Ln,"3 Beds, 5 Baths, 1,392 Sq. Ft.",Foster City,CA,94404
2,"$3,085-$6,080/mo",1030 Indian Wells Ave,"2 Beds, 2 Baths, 1,276 Sq. Ft.",Sunnyvale,CA,94085
3,"$7,300/mo",570 La Mesa Dr,"3 Beds, 2 Baths, 1,740 Sq. Ft.",Portola Valley,CA,94028
4,"$3,877-$6,563/mo",555 E Evelyn Ave,"3 Beds, 2 Baths, 1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,"$3,000/mo",425 2nd Ave,"1 Bed, 1 Bath, 851 Sq. Ft.",San Francisco,CA,94118
316,"$2,900/mo",280 Easy St #501,"2 Beds, 1 Bath, 894 Sq. Ft.",Mountain View,CA,94043
317,"$6,850/mo",6840 Charing Cross Rd,"5 Beds, 5 Baths, 3,908 Sq. Ft.",Berkeley,CA,94705
318,"$12,000/mo",111 30th Ave,"4 Beds, 3 Baths, 3,100 Sq. Ft.",San Francisco,CA,94121
319,"$3,450/mo",1320 Windswept Cmn,"3 Beds, 5 Baths, 1,757 Sq. Ft.",Livermore,CA,94550

hi

In [77]:

# first we need to remove the "/mo" part of the string
dff['Price'] = dff['Price'].str.replace("/mo", "")

# next, we need to remove the dash and everything after it
dff['Price'] = dff['Price'].str.replace(r'-.*', '')

# finally, we need to remove the comma separators in the numbers and add a "$" sign
dff['Price'] = "$" + dff['Price'].str.replace(',', '')

dff

C:\Users\yaboy\AppData\Local\Temp\ipykernel_9628\3565541582.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  dff['Price'] = dff['Price'].str.replace(r'-.*', '')

,Price,Address,Size,City,State,ZipCode
0,$$4472,350 Sharon Park Dr,"3 Beds, 2 Baths, 1,466 Sq. Ft.",Menlo Park,CA,94025
1,$$3305,55 Triton Park Ln,"3 Beds, 5 Baths, 1,392 Sq. Ft.",Foster City,CA,94404
2,$$3085,1030 Indian Wells Ave,"2 Beds, 2 Baths, 1,276 Sq. Ft.",Sunnyvale,CA,94085
3,$$7300,570 La Mesa Dr,"3 Beds, 2 Baths, 1,740 Sq. Ft.",Portola Valley,CA,94028
4,$$3877,555 E Evelyn Ave,"3 Beds, 2 Baths, 1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,$$3000,425 2nd Ave,"1 Bed, 1 Bath, 851 Sq. Ft.",San Francisco,CA,94118
316,$$2900,280 Easy St #501,"2 Beds, 1 Bath, 894 Sq. Ft.",Mountain View,CA,94043
317,$$6850,6840 Charing Cross Rd,"5 Beds, 5 Baths, 3,908 Sq. Ft.",Berkeley,CA,94705
318,$$12000,111 30th Ave,"4 Beds, 3 Baths, 3,100 Sq. Ft.",San Francisco,CA,94121
319,$$3450,1320 Windswept Cmn,"3 Beds, 5 Baths, 1,757 Sq. Ft.",Livermore,CA,94550

In [80]:
# remove the extra "$" sign
dff['Price'] = dff['Price'].str.replace("$", "")
# add the "$" sign
dff['Price'] = "$" + dff['Price']

dff

C:\Users\yaboy\AppData\Local\Temp\ipykernel_9628\1451249079.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  dff['Price'] = dff['Price'].str.replace("$", "")

,Price,Address,Size,City,State,ZipCode
0,$4472,350 Sharon Park Dr,"3 Beds, 2 Baths, 1,466 Sq. Ft.",Menlo Park,CA,94025
1,$3305,55 Triton Park Ln,"3 Beds, 5 Baths, 1,392 Sq. Ft.",Foster City,CA,94404
2,$3085,1030 Indian Wells Ave,"2 Beds, 2 Baths, 1,276 Sq. Ft.",Sunnyvale,CA,94085
3,$7300,570 La Mesa Dr,"3 Beds, 2 Baths, 1,740 Sq. Ft.",Portola Valley,CA,94028
4,$3877,555 E Evelyn Ave,"3 Beds, 2 Baths, 1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,$3000,425 2nd Ave,"1 Bed, 1 Bath, 851 Sq. Ft.",San Francisco,CA,94118
316,$2900,280 Easy St #501,"2 Beds, 1 Bath, 894 Sq. Ft.",Mountain View,CA,94043
317,$6850,6840 Charing Cross Rd,"5 Beds, 5 Baths, 3,908 Sq. Ft.",Berkeley,CA,94705
318,$12000,111 30th Ave,"4 Beds, 3 Baths, 3,100 Sq. Ft.",San Francisco,CA,94121
319,$3450,1320 Windswept Cmn,"3 Beds, 5 Baths, 1,757 Sq. Ft.",Livermore,CA,94550

In [81]:
# change the name of the "Price" column to "Monthly Rent"
dff.rename(columns={'Price': 'Monthly Rent'}, inplace=True)

dff

,Monthly Rent,Address,Size,City,State,ZipCode
0,$4472,350 Sharon Park Dr,"3 Beds, 2 Baths, 1,466 Sq. Ft.",Menlo Park,CA,94025
1,$3305,55 Triton Park Ln,"3 Beds, 5 Baths, 1,392 Sq. Ft.",Foster City,CA,94404
2,$3085,1030 Indian Wells Ave,"2 Beds, 2 Baths, 1,276 Sq. Ft.",Sunnyvale,CA,94085
3,$7300,570 La Mesa Dr,"3 Beds, 2 Baths, 1,740 Sq. Ft.",Portola Valley,CA,94028
4,$3877,555 E Evelyn Ave,"3 Beds, 2 Baths, 1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,$3000,425 2nd Ave,"1 Bed, 1 Bath, 851 Sq. Ft.",San Francisco,CA,94118
316,$2900,280 Easy St #501,"2 Beds, 1 Bath, 894 Sq. Ft.",Mountain View,CA,94043
317,$6850,6840 Charing Cross Rd,"5 Beds, 5 Baths, 3,908 Sq. Ft.",Berkeley,CA,94705
318,$12000,111 30th Ave,"4 Beds, 3 Baths, 3,100 Sq. Ft.",San Francisco,CA,94121
319,$3450,1320 Windswept Cmn,"3 Beds, 5 Baths, 1,757 Sq. Ft.",Livermore,CA,94550

,Monthly Rent,Address,Size,City,State,ZipCode
0,$4472,350 Sharon Park Dr,"1-3 Bed1-2 Bath810-1,466 Sq. Ft.",Menlo Park,CA,94025
1,$3305,55 Triton Park Ln,"1-3 Bed1-2.5 Bath760-1,392 Sq. Ft.",Foster City,CA,94404
2,$3085,1030 Indian Wells Ave,"1-2 Bed1-2 Bath563-1,276 Sq. Ft.",Sunnyvale,CA,94085
3,$7300,570 La Mesa Dr,"3 Beds2 Baths1,740 Sq. Ft.",Portola Valley,CA,94028
4,$3877,555 E Evelyn Ave,"0-3 Beds1-2 Bath644-1,355 Sq. Ft.",Mountain View,CA,94041
...,...,...,...,...,...,...
315,$3000,425 2nd Ave,1 Bed1 Bath851 Sq. Ft.,San Francisco,CA,94118
316,$2900,280 Easy St #501,2 Beds1 Bath894 Sq. Ft.,Mountain View,CA,94043
317,$6850,6840 Charing Cross Rd,"5 Beds3.5 Baths3,908 Sq. Ft.",Berkeley,CA,94705
318,$12000,111 30th Ave,"4 Beds3 Baths3,100 Sq. Ft.",San Francisco,CA,94121
319,$3450,1320 Windswept Cmn,"3 Beds3.5 Baths1,757 Sq. Ft.",Livermore,CA,94550

In [82]:
# Extract the values using regex
dff[['Beds', 'Baths', 'SqFt']] = dff['Size'].str.extract(r'(\d+) Beds, (\d+) Baths, (\d+,\d+) Sq. Ft.', expand=True)

# Replace NaN values with 0
dff['SqFt'] = dff['SqFt'].str.replace(',', '').astype(float).fillna(0).astype(int)


dff

,Monthly Rent,Address,Size,City,State,ZipCode,Beds,Baths,SqFt
0,$4472,350 Sharon Park Dr,"3 Beds, 2 Baths, 1,466 Sq. Ft.",Menlo Park,CA,94025,3,2,1466
1,$3305,55 Triton Park Ln,"3 Beds, 5 Baths, 1,392 Sq. Ft.",Foster City,CA,94404,3,5,1392
2,$3085,1030 Indian Wells Ave,"2 Beds, 2 Baths, 1,276 Sq. Ft.",Sunnyvale,CA,94085,2,2,1276
3,$7300,570 La Mesa Dr,"3 Beds, 2 Baths, 1,740 Sq. Ft.",Portola Valley,CA,94028,3,2,1740
4,$3877,555 E Evelyn Ave,"3 Beds, 2 Baths, 1,355 Sq. Ft.",Mountain View,CA,94041,3,2,1355
...,...,...,...,...,...,...,...,...,...
315,$3000,425 2nd Ave,"1 Bed, 1 Bath, 851 Sq. Ft.",San Francisco,CA,94118,NaN,NaN,0
316,$2900,280 Easy St #501,"2 Beds, 1 Bath, 894 Sq. Ft.",Mountain View,CA,94043,NaN,NaN,0
317,$6850,6840 Charing Cross Rd,"5 Beds, 5 Baths, 3,908 Sq. Ft.",Berkeley,CA,94705,5,5,3908
318,$12000,111 30th Ave,"4 Beds, 3 Baths, 3,100 Sq. Ft.",San Francisco,CA,94121,4,3,3100
319,$3450,1320 Windswept Cmn,"3 Beds, 5 Baths, 1,757 Sq. Ft.",Livermore,CA,94550,3,5,1757

In [83]:
# drop the size column
dff.drop(['Size'], axis=1, inplace=True)

dff

,Monthly Rent,Address,City,State,ZipCode,Beds,Baths,SqFt
0,$4472,350 Sharon Park Dr,Menlo Park,CA,94025,3,2,1466
1,$3305,55 Triton Park Ln,Foster City,CA,94404,3,5,1392
2,$3085,1030 Indian Wells Ave,Sunnyvale,CA,94085,2,2,1276
3,$7300,570 La Mesa Dr,Portola Valley,CA,94028,3,2,1740
4,$3877,555 E Evelyn Ave,Mountain View,CA,94041,3,2,1355
...,...,...,...,...,...,...,...,...
315,$3000,425 2nd Ave,San Francisco,CA,94118,NaN,NaN,0
316,$2900,280 Easy St #501,Mountain View,CA,94043,NaN,NaN,0
317,$6850,6840 Charing Cross Rd,Berkeley,CA,94705,5,5,3908
318,$12000,111 30th Ave,San Francisco,CA,94121,4,3,3100
319,$3450,1320 Windswept Cmn,Livermore,CA,94550,3,5,1757

In [84]:

# Replace NaN values with 0
dff['Beds'].fillna(0, inplace=True)
dff['Baths'].fillna(0, inplace=True)

dff

,Monthly Rent,Address,City,State,ZipCode,Beds,Baths,SqFt
0,$4472,350 Sharon Park Dr,Menlo Park,CA,94025,3,2,1466
1,$3305,55 Triton Park Ln,Foster City,CA,94404,3,5,1392
2,$3085,1030 Indian Wells Ave,Sunnyvale,CA,94085,2,2,1276
3,$7300,570 La Mesa Dr,Portola Valley,CA,94028,3,2,1740
4,$3877,555 E Evelyn Ave,Mountain View,CA,94041,3,2,1355
...,...,...,...,...,...,...,...,...
315,$3000,425 2nd Ave,San Francisco,CA,94118,0,0,0
316,$2900,280 Easy St #501,Mountain View,CA,94043,0,0,0
317,$6850,6840 Charing Cross Rd,Berkeley,CA,94705,5,5,3908
318,$12000,111 30th Ave,San Francisco,CA,94121,4,3,3100
319,$3450,1320 Windswept Cmn,Livermore,CA,94550,3,5,1757

# Final Result

In [85]:
dff

,Monthly Rent,Address,City,State,ZipCode,Beds,Baths,SqFt
0,$4472,350 Sharon Park Dr,Menlo Park,CA,94025,3,2,1466
1,$3305,55 Triton Park Ln,Foster City,CA,94404,3,5,1392
2,$3085,1030 Indian Wells Ave,Sunnyvale,CA,94085,2,2,1276
3,$7300,570 La Mesa Dr,Portola Valley,CA,94028,3,2,1740
4,$3877,555 E Evelyn Ave,Mountain View,CA,94041,3,2,1355
...,...,...,...,...,...,...,...,...
315,$3000,425 2nd Ave,San Francisco,CA,94118,0,0,0
316,$2900,280 Easy St #501,Mountain View,CA,94043,0,0,0
317,$6850,6840 Charing Cross Rd,Berkeley,CA,94705,5,5,3908
318,$12000,111 30th Ave,San Francisco,CA,94121,4,3,3100
319,$3450,1320 Windswept Cmn,Livermore,CA,94550,3,5,1757

In [86]:
#export data frame as a csv file, ready for further analysis
dff.to_csv("cleanedrental.csv", index=False)

print("done")

done